name: Preview Deploy
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 12.16

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn run --max-old-space-size=7168 build-storybook

      - name: Deploy
        if: success()
        run: |
          aws s3 sync .out s3://${S3_PROJECT_BUCKET}/storybook-${{ github.event.pull_request.number }} --delete --acl public-read --cache-control 'max-age=2419200, must-revalidate, public'
          aws s3 cp s3://${S3_PROJECT_BUCKET}/storybook-${{ github.event.pull_request.number }}/index.html s3://${S3_PROJECT_BUCKET}/storybook-${{ github.event.pull_request.number }}/index.html --metadata-directive REPLACE --cache-control 'no-cache, no-store, must-revalidate'
        env:
          S3_PROJECT_BUCKET: ${{ secrets.S3_PROJECT_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Update Status
        if: success()
        uses: ./.github/actions/status-update
        with:
          REPO_TOKEN: ${{ secrets.GPR_TOKEN }}
