name: Publish Package

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    # skip for automatic commits from vas-build
    if: github.actor != 'vas-build'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.GPR_TOKEN }}
          repository: francoro-ms/Morpheus-test
          event-type: vas-fe-published
          client-payload: "{actor: ${{secrets.GITHUB_ACTOR}}}"
